image: python:3.6
clone:
  depth: full

stepdefinitions:
  - testing: &testing
      name: Python testing
      caches:
        - pip
      script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pytest --cov=hazenlib --cov=app --cov-report xml --junitxml=junit.xml tests/


      services:
        - postgres

  - reporting: &reporting
      name: Uploading reports
      script:
      - pipe: sonarsource/sonarcloud-scan:1.0.1
        variables:
          SONAR_TOKEN: ${SONAR_TOKEN}
          EXTRA_ARGS: '-Dsonar.branch.name=$BITBUCKET_BRANCH -X -Dsonar.python.coverage.reportPaths=**/coverage.xml -Dsonar.python.xunit.reportPath=**/junit.xml'
         
      - bash <(curl -f .coverage.xml  https://codecov.io/bash) -t $CODECOV_TOKEN

  - deploying: &deploying
      name: Deploy to Heroku and dockerhub
      deployment: staging   # set to test, staging or production
      # trigger: manual  # uncomment to have a manual step
      script:
        - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $BITBUCKET_BRANCH:master
        - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
        - docker build -t gsttmriphysics/hazen .
        - docker push gsttmriphysics/hazen
        - docker tag gsttmriphysics/hazen:latest gsttmriphysics/hazen:build_$BITBUCKET_BUILD_NUMBER
        - docker push gsttmriphysics/hazen:build_$BITBUCKET_BUILD_NUMBER
      services:
        - docker

pipelines:
  branches:
    master:
      - step: *testing
      - step: *reporting
      - step: *deploying
    release/*:
      - step: *testing
      - step: *reporting
      - step: *deploying
    hotfix/*:
      - step: *testing
      - step: *reporting
#      - step: *deploying // should we be deploying hotfix builds? more controlled to merge into master and deploy from there
  default:
    - step: *testing
    - step: *reporting

definitions:
  services:
    docker:
        memory: 2048
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'hazen_test'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'