name: hazen-3.9-miniforge

dependencies:
  - pip=21.3.1
  - python=3.9.7
  - scikit-image
#  - psycopg2-binary
#  - pip:
#    - SQLAlchemy_Utils==0.33.11
#    - alembic==1.0.10
#    - celery==4.3.1
#    - numpy==1.21.0
#    - Werkzeug==0.15.4
#    - opencv-python==4.5.4.58
#    - Flask_Migrate==2.5.1
#    - pytest>=6.2
#    - coverage>=6.0.2
#    - Flask_Moment==0.7.0
#    - flask_heroku==0.1.9
#    - Flask==1.0.3
#    - pydicom==1.4.1
#    - WTForms==2.2.1
#    - Flask_Dropzone==1.5.3
#    - Flask_Mail==0.9.1
#    - Flask_Login==0.4.1
#    - Flask_Bootstrap4==4.0.2
#    - imutils==0.5.3
#    - matplotlib==3.4.3
#    - Flask_SQLAlchemy==2.4.0
#    - scipy==1.7.2
#    - docopt==0.6.2
#    - SQLAlchemy==1.3.3
#    - Flask_WTF==0.14.2
#    - flask_bootstrap==3.3.7.1
#    - PyJWT==1.7.1
#    - gunicorn==19.9.0
##    - psycopg2-binary==2.8.4
#    - arrow==0.13.2
#    - amqp==2.4.2
#    - sphinxcontrib-needs==0.4.3
#    - sphinxcontrib-napoleon
#    - sphinx_rtd_theme
#    - m2r
#    - python-dateutil
#    - email_validator
#    - colorlog

