"""empty message

Revision ID: 84124366c36a
Revises: 8ca431ff665f
Create Date: 2020-01-19 19:43:01.850081

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84124366c36a'
down_revision = '8ca431ff665f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('followed_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_followed_uuid_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_uuid_fkey')
    )
    # ### end Alembic commands ###
