"""add Fact status

Revision ID: 8ca431ff665f
Revises: 55de84fb328d
Create Date: 2019-01-04 23:02:59.857380

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8ca431ff665f'
down_revision = '55de84fb328d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'status')
    # ### end Alembic commands ###
