"""empty message

Revision ID: 9c6384cd2c43
Revises: cb1c369dca73
Create Date: 2019-01-02 10:52:38.390135

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
from app import db

# revision identifiers, used by Alembic.
revision = '9c6384cd2c43'
down_revision = 'cb1c369dca73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisition', sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    acquisition = sa.sql.table('acquisition', sa.Column('created_at'))
    op.execute(acquisition.update().values(created_at=db.func.now()))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('acquisition', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('acquisition', 'created_at')
    # ### end Alembic commands ###
