"""empty message

Revision ID: cb1c369dca73
Revises: 5b01b2c8311b
Create Date: 2019-01-02 10:32:30.073713

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app import db


# revision identifiers, used by Alembic.
revision = 'cb1c369dca73'
down_revision = '5b01b2c8311b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    user = sa.sql.table('user', sa.Column('created_at'))
    op.execute(user.update().values(created_at=db.func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
