"""add Fact and ProcessTask

Revision ID: ec246725742c
Revises: 968caeb7fe6c
Create Date: 2019-01-04 17:43:47.085965

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec246725742c'
down_revision = '968caeb7fe6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_task',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('docstring', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('acquisition_id', postgresql.UUID(), nullable=True),
    sa.Column('process_task', postgresql.UUID(), nullable=True),
    sa.Column('process_task_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dataF', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.ForeignKeyConstraint(['process_task'], ['process_task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact')
    op.drop_table('process_task')
    # ### end Alembic commands ###
