# This workflow will install Python dependencies, and run the hazen through the CLI to check functionality
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: CLI test

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.9', '3.10' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install hazen
      run: |
        python setup.py install

    - name: test snr
      if: always()  # will always run regardless of whether previous step fails - useful to ensure all CLI functions tested
      run: |
        hazen snr tests/data/snr/Siemens --report
