on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install hazen
      run: |
        python setup.py install

    - name: test snr
      if: always()  # will always run regardless of whether previous step fails - useful to ensure all CLI functions tested
      run: |
        hazen snr tests/data/snr/Siemens --report

